- constraint:
    domainName: "default"
  value:
    history.advancedVisibilityWritingMode: "on"

- constraint:
    domainName: "domain"
  value:
    history.advancedVisibilityWritingMode: "on"

- constraint:
    taskListName: "task-list"
    domainName: "default"
    taskType: "decision"
  value:
    frontend.rateLimitPerSecond: 2000.0
