# Temporal Web UI HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: temporal-web
  namespace: temporal
  annotations:
    konghq.com/cluster-plugins: "global-rate,oidc-auth"
spec:
  parentRefs:
  - name: edge
    namespace: gateway
  hostnames:
  - "temporal.aldous.info"  # Replace with your domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: temporal-web
      port: 8080