---
x-build-env:

  BUILDKIT_INLINE_CACHE: "1"
  BUILDKIT_PROGRESS: plain
  DOCKER_BUILDKIT: "1"

name: mindfield

services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - type: bind
        source: ./docs
        target: /docs
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    command:
      - serve
      - --dev-addr=0.0.0.0:8000
    working_dir: /docs
    cpus: 0.25
    mem_limit: "134217728"

  postgraphile:
    image: graphile/postgraphile:latest
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    command:
      - --connection
      - postgres://mindfield:mindfield_dev_password@postgres:5432/mindfield
      - --schema
      - public
      - --watch
      - --enhance-graphiql
      - --dynamic-json
      - --no-setof-functions-contain-nulls
      - --no-ignore-rbac
      - --show-error-stack=json
      - --extended-errors
      - hint,detail,errcode
      - --export-schema-graphql
      - /tmp/schema.graphql
      - --graphiql
      - /graphiql
      - --port
      - "5000"
    cpus: 0.5
    mem_limit: "268435456"

  redoc:
    image: redocly/redoc:latest
    depends_on:
      api:
        condition: service_started
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 0.25
    mem_limit: "134217728"

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    depends_on:
      api:
        condition: service_started
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 0.25
    mem_limit: "134217728"
