---
x-build-env:

  BUILDKIT_INLINE_CACHE: "1"
  BUILDKIT_PROGRESS: plain
  DOCKER_BUILDKIT: "1"

name: mindfield

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      args:
        NODE_MAJOR: ${NODE_MAJOR}
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    cpus: 1
    mem_limit: "536870912"
    read_only: true
    tmpfs:
      - /tmp

  render:
    build:
      context: .
      dockerfile: docker/Dockerfile.services
      args:
        NODE_MAJOR: ${NODE_MAJOR}
        SERVICE: render
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    command:
      - node
      - dist/main.js
    cpus: 1
    mem_limit: "536870912"
    read_only: true
    tmpfs:
      - /tmp

  submission:
    build:
      context: .
      dockerfile: docker/Dockerfile.services
      args:
        NODE_MAJOR: ${NODE_MAJOR}
        SERVICE: submission
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    command:
      - node
      - dist/main.js
    cpus: 0.5
    mem_limit: "268435456"
    read_only: true
    tmpfs:
      - /tmp

  transform:
    build:
      context: .
      dockerfile: docker/Dockerfile.services
      args:
        NODE_MAJOR: ${NODE_MAJOR}
        SERVICE: transform
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    command:
      - node
      - dist/main.js
    cpus: 0.5
    mem_limit: "268435456"
    read_only: true
    tmpfs:
      - /tmp

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        NODE_MAJOR: ${NODE_MAJOR}
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      api:
        condition: service_started
        required: true
    volumes:
      - type: bind
        source: .
        target: /repo
        bind:
          create_host_path: true
      - type: volume
        source: web_next
        target: /repo/.next
        volume: {}
      - type: volume
        source: web_node_modules
        target: /repo/apps/web/node_modules
        volume: {}
    env_file:
      - .env
    networks:
      frontend: null
    cpus: 1
    mem_limit: "536870912"
    read_only: true
    tmpfs:
      - /tmp
      - /app/.next/cache
