---
x-build-env:

  BUILDKIT_INLINE_CACHE: "1"
  BUILDKIT_PROGRESS: plain
  DOCKER_BUILDKIT: "1"

name: mindfield

services:
  minio:
    image: minio/minio:latest
    volumes:
      - type: volume
        source: minio_data
        target: /data
        volume: {}
    env_file:
      - .env
    networks:
      backend: null
    command:
      - server
      - /data
      - --console-address
      - :9001
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/minio/health/live
      timeout: 20s
      interval: 30s
      retries: 3
    cpus: 0.5
    mem_limit: "268435456"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: ./services/pgbouncer
        target: /etc/pgbouncer
        bind:
          create_host_path: true
    user: root
    env_file:
      - .env
    networks:
      backend: null
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -h
        - localhost
        - -p
        - "5432"
        - -U
        - "${DB_USER}"
        - -d
        - "${DB_NAME}"
      timeout: 5s
      interval: 10s
      retries: 5
    cpus: 0.25
    mem_limit: "67108864"

  postgres:
    image: postgres:17-alpine
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume: {}
      - type: bind
        source: ./services/postgres/init
        target: /docker-entrypoint-initdb.d
        bind:
          create_host_path: true
    environment:
      POSTGRES_DB: ${MINDFIELD_POSTGRES_DB}
      POSTGRES_USER: ${MINDFIELD_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MINDFIELD_POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      backend: null
    command:
      - postgres
      - -c
      - shared_buffers=256MB
      - -c
      - effective_cache_size=1GB
      - -c
      - maintenance_work_mem=64MB
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - wal_buffers=16MB
      - -c
      - default_statistics_target=100
      - -c
      - random_page_cost=1.1
      - -c
      - effective_io_concurrency=200
      - -c
      - password_encryption=md5
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U mindfield
      timeout: 5s
      interval: 10s
      retries: 5
    cpus: 1
    mem_limit: "536870912"

  redis:
    image: redis:7-alpine
    volumes:
      - type: volume
        source: redis_data
        target: /data
        volume: {}
    env_file:
      - .env
    networks:
      backend: null
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - 128mb
      - --maxmemory-policy
      - allkeys-lru
      - --save
      - "900"
      - "1"
      - --save
      - "300"
      - "10"
      - --save
      - "60"
      - "10000"
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 10s
      retries: 5
    cpus: 0.5
    mem_limit: "268435456"
