# Modern Keycloak X Configuration
image:
  tag: "26.0.7"

# Number of replicas
replicas: 1

# Disable embedded PostgreSQL
postgresql:
  enabled: false

# Command to start Keycloak in production mode
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"

# Environment variables for Keycloak configuration
extraEnv: |
  - name: KC_DB
    value: postgres
  - name: KC_DB_URL
    value: jdbc:postgresql://postgres-postgresql.data.svc.cluster.local:5432/keycloak
  - name: KC_DB_USERNAME
    value: keycloak
  - name: KC_DB_PASSWORD
    value: keycloak
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin123
  - name: KC_HOSTNAME
    value: keycloak.aldous.info
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_CACHE
    value: "local"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"

# Resources
resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: 500m
