# PostgreSQL Configuration
image:
  tag: "16"

auth:
  postgresPassword: "postgres"
  database: "mindfield"
  username: "mindfield"
  password: "mindfield"

primary:
  persistence:
    enabled: true
    storageClass: "microk8s-hostpath"
    size: 50Gi
    accessModes:
      - ReadWriteOnce
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL

  initdb:
    scripts:
      init.sql: |
        CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        CREATE EXTENSION IF NOT EXISTS "pgcrypto";
        CREATE EXTENSION IF NOT EXISTS "citext";

readReplicas:
  replicaCount: 0

metrics:
  enabled: false

postgresqlSharedPreloadLibraries: "pg_stat_statements"

postgresqlConfiguration:
  max_connections: "200"
  shared_buffers: "128MB"
  effective_cache_size: "512MB"
  maintenance_work_mem: "64MB"
  checkpoint_completion_target: "0.9"
  wal_buffers: "16MB"
  default_statistics_target: "100"
  random_page_cost: "1.1"
  effective_io_concurrency: "200"
  work_mem: "4MB"
  min_wal_size: "1GB"
  max_wal_size: "4GB"
  max_worker_processes: "8"
  max_parallel_workers_per_gather: "2"
  max_parallel_workers: "8"
  max_parallel_maintenance_workers: "2"
