
CREATE ROLE keycloak WITH LOGIN PASSWORD 'password';
CREATE DATABASE keycloak OWNER keycloak;
GRANT CONNECT ON DATABASE keycloak TO keycloak;

CREATE ROLE kong WITH LOGIN PASSWORD 'password';
CREATE DATABASE kong OWNER kong;
GRANT CONNECT ON DATABASE kong TO kong;

CREATE ROLE pgadmin WITH LOGIN PASSWORD 'password';
CREATE DATABASE pgadmin OWNER pgadmin;
GRANT CONNECT ON DATABASE pgadmin TO pgadmin;

CREATE ROLE grafana WITH LOGIN PASSWORD 'password';
CREATE DATABASE grafana OWNER grafana;
GRANT CONNECT ON DATABASE grafana TO grafana;

CREATE ROLE sonarqube WITH LOGIN PASSWORD 'password';
CREATE DATABASE sonarqube OWNER sonarqube;
GRANT CONNECT ON DATABASE sonarqube TO sonarqube;
