
CREATE ROLE keycloak WITH LOGIN PASSWORD 'password';
CREATE DATABASE keycloak OWNER keycloak;
GRANT CONNECT ON DATABASE keycloak TO keycloak;

CREATE ROLE kong WITH LOGIN PASSWORD 'password';
CREATE DATABASE kong OWNER kong;
GRANT CONNECT ON DATABASE kong TO kong;

CREATE ROLE pgadmin WITH LOGIN PASSWORD 'password';
CREATE DATABASE pgadmin OWNER pgadmin;
GRANT CONNECT ON DATABASE pgadmin TO pgadmin;
