global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs: [{targets: ["localhost:9090"]}]
  - job_name: otel-collector-internal
    static_configs: [{targets: ["collector:8888"]}]
  - job_name: otel-collector
    honor_labels: true
    static_configs: [{targets: ["collector:8889"]}]
