---
x-build-env:

  BUILDKIT_INLINE_CACHE: "1"
  BUILDKIT_PROGRESS: plain
  DOCKER_BUILDKIT: "1"

name: mindfield

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      mailhog:
        condition: service_healthy
        required: true
      pgbouncer:
        condition: service_healthy
        required: true
    volumes:
      - type: volume
        source: keycloak_data
        target: /opt/keycloak/data
        volume: {}
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    command:
      - start
    cpus: 0.5
    mem_limit: "536870912"

  keycloak-configure:
    image: curlimages/curl:latest
    depends_on:
      keycloak:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: ./services/keycloak/configure.sh
        target: /configure.sh
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
    command:
      - sh
      - /configure.sh
    restart: "no"
    cpus: 0.25

  kong:
    build:
      context: .
      dockerfile: docker/Dockerfile.kong
      cache_from:
        - type=registry,ref=localhost:5001/mindfield-cache
      cache_to:
        - type=registry,ref=localhost:5001/mindfield-cache,mode=max
    depends_on:
      kong-bootstrap:
        condition: service_completed_successfully
      pgbouncer:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - frontend
      - backend
    restart: on-failure

  kong-bootstrap:
    image: kong/kong-gateway:latest
    depends_on:
      pgbouncer:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend
    command: kong migrations bootstrap
    restart: on-failure

  kong-configure:
    image: curlimages/curl:latest
    depends_on:
      kong:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: ./services/kong/configure.sh
        target: /configure.sh
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
    command:
      - sh
      - /configure.sh
    restart: "no"
    cpus: 0.25
