---
x-build-env:

  BUILDKIT_INLINE_CACHE: "1"
  BUILDKIT_PROGRESS: plain
  DOCKER_BUILDKIT: "1"

name: mindfield

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    volumes:
      - type: volume
        source: opensearch_data
        target: /usr/share/opensearch/data
        volume: {}
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: mindfield-cluster
      discovery.type: single-node
      node.name: opensearch
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 1
    mem_limit: "1073741824"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    depends_on:
      opensearch:
        condition: service_started
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 0.5
    mem_limit: "536870912"
