USER-SUPPLIED VALUES:
akhq:
  connections:
    local:
      properties:
        bootstrap.servers: kafka-kafka-bootstrap.messaging.svc.cluster.local:9092
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
  podSecurityContext:
    runAsNonRoot: true
  security:
    default-roles:
    - topic/read
  server:
    servlet:
      context-path: /
