# Keycloak HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: auth
  annotations:
    konghq.com/cluster-plugins: "global-rate"
spec:
  parentRefs:
  - name: edge
    namespace: gateway
  hostnames:
  - "keycloak.aldous.info"  # Replace with your domain
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: keycloak
      port: 8080