---
name: mindfield

services:
  caddy:
    build:
      context: .
      dockerfile: docker/Dockerfile.caddy
      cache_from:
        - type=registry,ref=localhost:5001/cache
      cache_to:
        - type=registry,ref=localhost:5001/cache,mode=max
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: /var/log/caddy/
        target: /var/log/caddy/
        bind:
          create_host_path: true
      - type: bind
        source: ./services/caddy/Caddyfile
        target: /etc/caddy/Caddyfile
        bind:
          create_host_path: true
    env_file:
      - .env
    ports:
      - mode: ingress
        target: 80
        published: "80"
        host_ip: 0.0.0.0
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        host_ip: 0.0.0.0
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        host_ip: 0.0.0.0
        protocol: udp
      - mode: ingress
        target: 2019
        published: "2019"
        host_ip: 0.0.0.0
        protocol: tcp
    networks:
      backend: null
      frontend: null
      monitoring: null
    restart: always
    healthcheck:
      test:
        - CMD
        - "true"
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 60s
    cpus: 0.25
    mem_limit: "134217728"

  mailhog:
    image: mailhog/mailhog:latest
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    restart: always
    healthcheck:
      test:
        - CMD
        - "true"
      timeout: 10s
      interval: 5s
      retries: 12
      start_period: 60s
    cpus: 0.25
    mem_limit: "134217728"

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    restart: always
    healthcheck:
      test:
        - CMD
        - "true"
      interval: 5s
      timeout: 10s
      retries: 12
      start_period: 60s
    cpus: 0.5
    mem_limit: "268435456"
