---
name: mindfield

services:

  opensearch:
    image: opensearchproject/opensearch:latest
    volumes:
      - type: bind
        source: ./data/opensearch
        target: /usr/share/opensearch/data
        bind:
          create_host_path: true
    environment:
      bootstrap.memory_lock: "true"
      cluster.name: opensearch-cluster
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 1
    mem_limit: "1073741824"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  search:
    image: opensearchproject/opensearch-dashboards:latest
    depends_on:
      opensearch:
        condition: service_started
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 0.5
    mem_limit: "536870912"
