# Global rate limiting (cluster-scoped)
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate
  labels:
    global: "true"
plugin: rate-limiting
config:
  minute: 6000
  policy: local  # Change to 'redis' for HA with Redis
  limit_by: ip
  hide_client_headers: false

---
# Redis-based rate limiting (HA option)
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-rate-redis
  labels:
    global: "true"
plugin: rate-limiting
config:
  minute: 6000
  policy: redis
  redis_host: redis.gateway.svc.cluster.local
  redis_port: 6379
  limit_by: ip
  hide_client_headers: false

---
# OIDC Authentication (cluster-scoped)
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: oidc-auth
  labels:
    global: "true"
plugin: openid-connect
config:
  issuer: "https://keycloak.aldous.info/realms/master"
  client_id: "kong"
  client_secret:
    key: client-secret
    name: keycloak-oidc-secret
  redirect_uri: "https://aldous.info/auth"
  scope: "openid profile email"
  response_type: "code"
  ssl_verify: true
  session_secret:
    key: session-secret
    name: kong-session-secret