---
name: mindfield

services:

  sonarqube:
    image: sonarqube:community
    depends_on:
      pgbouncer:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: data/sonarqube/es7
        target: /opt/sonarqube/data/es7
        bind:
          create_host_path: true
      - type: bind
        source: data/sonarqube/logs
        target: /opt/sonarqube/logs
        bind:
          create_host_path: true
      - type: bind
        source: data/sonarqube/extensions
        target: /opt/sonarqube/extensions
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    cpus: 1
    mem_limit: "2147483648"

# 
#   storybook:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.storybook
#       args:
#         NODE_MAJOR: ${NODE_MAJOR}
#       cache_from:
#         - type=registry,ref=localhost:5001/mindfield-cache
#       cache_to:
#         - type=registry,ref=localhost:5001/mindfield-cache,mode=max
#     volumes:
#       - type: bind
#         source: ./core/ui
#         target: /app/core/ui
#         bind:
#           create_host_path: true
#       - type: bind
#         source: ./apps/web
#         target: /app/apps/web
#         bind:
#           create_host_path: true
#       - type: bind
#         source: .
#         target: /app
#         bind:
#           create_host_path: true
#       - type: volume
#         source: storybook_next
#         target: /app/.next
#         volume: {}
#       - type: volume
#         source: storybook_node_modules
#         target: /app/apps/web/node_modules
#         volume: {}
#     env_file:
#       - .env
#     networks:
#       frontend: null
#     cpus: 0.5
#     mem_limit: "536870912"
