---
name: mindfield

services:
  keycloak:
    ports:
      - '0.0.0.0:8080:8080'
      - '0.0.0.0:9090:9000' # 9090

  kong:
    ports:
      - '0.0.0.0:8000:8000'
      - '0.0.0.0:8001:8001'
      - '0.0.0.0:8002:8002'
      - '0.0.0.0:8003:8003'
      - '0.0.0.0:8004:8004'

  mailhog:
    ports:
      - '0.0.0.0:1025:1025'
      - '0.0.0.0:8025:8025'

  minio:
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:9001:9001'

  pgadmin:
    ports:
      - '0.0.0.0:8081:80' # 8081

  pgbouncer:
    ports:
      - '0.0.0.0:5433:5433'

  postgres:
    ports:
      - '0.0.0.0:5432:5432'

  redis:
    ports:
      - '0.0.0.0:6379:6379'

  redisinsight:
    ports:
      - '0.0.0.0:5540:5540'

  alertmanager:
    ports:
      - "0.0.0.0:9093:9093"

#
#   api:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   blackbox-exporter:
#     ports:
#       - "0.0.0.0:9115:9115"
#
#   grafana:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   grapesjs:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   jaeger:
#     ports:
#       - "0.0.0.0:14268:14268"
#       - "0.0.0.0:16686:16686"
#

#   loki:
#     ports:
#       - "0.0.0.0:3100:3100"

#   mkdocs:
#     ports:
#       - "0.0.0.0:8000:8000"
#
#   node-exporter:
#     ports:
#       - "0.0.0.0:9100:9100"
#
#   opensearch:
#     ports:
#       - "0.0.0.0:9200:9209200"
#       - "0.0.0.0:9600:9600"
#
#   opensearch-dashboards:
#     ports:
#       - "0.0.0.0:5601:5601"
#
#   otel-collector:
#     ports:
#       - "0.0.0.0:4317:4317"
#       - "0.0.0.0:4318:4318"
#       - "0.0.0.0:8888:8888"
#       - "0.0.0.0:8889:8889"
#
#   pgadmin:
#     ports:
#       - "0.0.0.0:80:80"
#

#   postgraphile:
#     ports:
#       - "0.0.0.0:5000:5000"
#
#   presidio-analyzer:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   presidio-anonymizer:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   presidio-image-redactor:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   prometheus:
#     ports:
#       - "0.0.0.0:9090:9090"

#
#   redoc:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   render:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   sonarqube:
#     ports:
#       - "0.0.0.0:9000:9000"
#
#   storybook:
#     ports:
#       - "0.0.0.0:6006:6006"
#
#   submission:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   swagger-ui:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   transform:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   trivy:
#     ports:
#       - "0.0.0.0:8080:8080"
#
#   uptime-kuma:
#     ports:
#       - "0.0.0.0:3000:3000"
#
#   web:
#     ports:
#       - "0.0.0.0:3000:3000"
