micronaut:
  security:
    enabled: false
  server:
    context-path: ""

akhq:
  server:
    customHttpResponseHeaders:
      - name: "Content-Security-Policy"
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' http: https: ws:; manifest-src 'self'; worker-src 'self' blob:; frame-ancestors 'self'; form-action 'self'; object-src 'none'"
      - name: "X-Permitted-Cross-Domain-Policies"
        value: "none"
  clients-defaults:
    admin:
      properties:
        client.id: "akhq-admin"
    producer:
      properties:
        client.id: "akhq-producer"
        acks: all
    consumer:
      properties:
        client.id: "akhq-consumer"
        isolation.level: read_committed
        default.api.timeout.ms: 60000

  connections:
    kafka:
      properties:
        bootstrap.servers: "kafka:9092"
      schema-registry:
        url: "http://schema-registry:8081"     
        type: "confluent"
      connect:
        - name: kafka-connect
          url: "http://kafka-connect:8083"     

logger:
  levels:
    org.akhq.modules.KafkaModule: TRACE
    io.micronaut.context.env: TRACE

