FROM caddy:2.10.0-builder AS builder

RUN xcaddy build \
    --with github.com/RussellLuo/caddy-ext/ratelimit \
    --with github.com/pberkel/caddy-storage-redis \
    --with github.com/greenpau/caddy-security

FROM caddy:2.10.0

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY services/caddy/Caddyfile /etc/caddy/Caddyfile

EXPOSE 80 443

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
