FROM caddy:builder AS builder
RUN \
    --mount=type=cache,id=go-build,target=/root/.cache/go-build \
    --mount=type=cache,id=go-mod,target=/go/pkg/mod \
    xcaddy build \
    --with github.com/RussellLuo/caddy-ext/ratelimit

FROM caddy:alpine AS runtime
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY services/caddy/Caddyfile /etc/caddy/Caddyfile

EXPOSE 80 443
