ARG NODE_MAJOR=24
FROM node:${NODE_MAJOR}-alpine AS base
ENV PNPM_STORE_PATH=/root/.pnpm-store
RUN --mount=type=cache,id=apk-cache,target=/var/cache/apk apk add --no-cache python3 make g++ && corepack enable && corepack prepare pnpm@latest --activate && pnpm config set node-linker hoisted
WORKDIR /app
