# Temporal Helm values template
server:
  image:
    tag: "1.28.0"
  config:
    persistence:
      default:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgresql.data.svc.cluster.local"
          port: 5432
          database: "temporal"
          user: "temporal"
          password: "${TEMPORAL_DB_PASSWORD}"
          maxConns: 20
          maxConnLifetime: "1h"
      visibility:
        driver: "sql"
        sql:
          driver: "postgres"
          host: "postgresql.data.svc.cluster.local"
          port: 5432
          database: "temporal_visibility"
          user: "temporal"
          password: "${TEMPORAL_VIS_DB_PASSWORD}"
          maxConns: 10
          maxConnLifetime: "1h"

# Disable Cassandra
cassandra:
  enabled: false

# Disable built-in PostgreSQL
postgresql:
  enabled: false

# Web UI configuration
web:
  enabled: true
  service:
    type: ClusterIP
    port: 8080

# Admin tools
admintools:
  enabled: true

# Schema setup job
schema:
  setup:
    enabled: true
  update:
    enabled: true