---
name: mindfield

services:

  analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    depends_on:
      redis:
        condition: service_healthy
        required: true
    volumes:
      - type: bind
        source: services/analyzer/healthcheck.sh
        target: /healthcheck.sh
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
    healthcheck:
      test:
        - CMD-SHELL
        - /healthcheck.sh
      timeout: 20s
      interval: 30s
      retries: 3
    cpus: 1
    mem_limit: "1073741824"

  anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    depends_on:
      analyzer:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    cpus: 0.5
    mem_limit: "536870912"

  redactor:
    image: mcr.microsoft.com/presidio-image-redactor:latest
    depends_on:
      analyzer:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
    cpus: 1
    mem_limit: "1073741824"
