---
name: mindfield

services:

  docs:
    image: squidfunk/mkdocs-material:latest
    volumes:
      - type: bind
        source: ./docs
        target: /docs
        bind:
          create_host_path: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    command:
      - serve
      - --dev-addr=0.0.0.0:8005
    working_dir: /docs
    cpus: 0.25
    mem_limit: "134217728"
 
  postgraphile:
    image: graphile/postgraphile:latest
    depends_on:
      postgres:
        condition: service_healthy
        required: true
    env_file:
      - .env
    networks:
      backend: null
      frontend: null
    command:
      - --connection
      - postgres://postgraphile:${POSTGRAPHILE_DB_PASSWORD}@pgbouncer:5433/${NAME}
      - --schema
      - public
      - --watch
      - --enhance-graphiql
      - --dynamic-json
      - --no-setof-functions-contain-nulls
      - --no-ignore-rbac
      - --show-error-stack=json
      - --extended-errors
      - hint,detail,errcode
      - --export-schema-graphql
      - /tmp/schema.graphql
      - --graphiql
      - /graphiql
      - --port
      - "5002"
    cpus: 0.5
    mem_limit: "268435456"
