---
name: mindfield

networks:

  backend:
    name: mindfield_backend
    driver: bridge

  default:
    name: mindfield_default

  frontend:
    name: mindfield_frontend
    driver: bridge

  monitoring:
    name: mindfield_monitoring
    driver: bridge

volumes:

  storybook_next:
    name: mindfield_storybook_next

  storybook_node_modules:
    name: mindfield_storybook_node_modules

  web_next:
    name: mindfield_web_next

  web_node_modules:
    name: mindfield_web_node_modules
