# Keycloak OIDC client secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-secret
  namespace: gateway
type: Opaque
data:
  client-secret: a29uZy1jbGllbnQtc2VjcmV0  # base64: kong-client-secret

---
# Kong session secret
apiVersion: v1
kind: Secret
metadata:
  name: kong-session-secret
  namespace: gateway
type: Opaque
data:
  session-secret: c2Vzc2lvbi1zZWNyZXQtZm9yLWtvbmc=  # base64: session-secret-for-kong

---
# External Secret for Keycloak OIDC (production)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-oidc
  namespace: gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets-store
    kind: ClusterSecretStore
  target:
    name: keycloak-oidc-secret
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: keycloak-oidc-client-secret
      property: secret

---
# External Secret for Kong session (production)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kong-session
  namespace: gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets-store
    kind: ClusterSecretStore
  target:
    name: kong-session-secret
    creationPolicy: Owner
  data:
  - secretKey: session-secret
    remoteRef:
      key: kong-session-secret
      property: secret