image:
  repository: graphile/postgraphile
  tag: "4.13.0"
  pullPolicy: IfNotPresent
env:
  DATABASE_URL: "postgres://mindfield:mindfield@postgres-postgresql:5432/mindfield"
  POSTGRAPHILE_OPTIONS: "--enhance-graphiql --no-ignore-rbac --cors"
service:
  type: ClusterIP
  port: 5000
resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 200m
